### ISSUE TITLE
sasl string-to-utf8-lisp has an erro on some condition 

### ISSUE THREAD

**Issue by evilbinary** [legoscia/cl-sasl#2]
string-to-utf8-lisp  this function has an error ,when the string is nil.It runs erro.And before it we must check the string if it is a nil. The code below:
defun string-to-utf8-lisp (string)  
 "Convert STRING to UTF-8.  Return a vector of unsigned-bytes."  
 (if (eq string nil)  
   (setf string ""))  
and so on........)

**Comment by ghard** [comment]
Here's my observation: 
```
CL-USER> (lisp-implementation-type)
"SBCL"
CL-USER> (lisp-implementation-version)
"1.4.16"
CL-USER> (handler-case (cl-sasl::string-to-utf8-lisp nil) (error (e) e))
#<TYPE-ERROR expected-type: VECTOR datum: NIL>
```

Also SBCL has its own call to convert strings to octets, which should work here, but that one also signals a condition when a nil is passed to it. 

I had a problem with sasl-plain aut using CL-XMPP, and this quick hack solved it:

```common lisp
(defmethod client-step ((c plain) server-input)
  (declare (ignore server-input))
  (ecase (state c)
    (:start
     (setf (state c) :sent)
     (concatenate '(vector (unsigned-byte 8))
		  (string-to-utf8 (or (authz-id c) "")) '(0)
		  (string-to-utf8 (or (authc-id c) "")) '(0)
		  (string-to-utf8 (get-password (password c)))))
    (:sent
     :success)))
```
I can send a pull request which would also add conditional compilation for sbcl to use sb-ext:octets-to-strings if you like.

**Comment by ghard** [comment]
Aww I just noticed there's an old pull request with similar fix that already has been merged, but the fixed version hasn't been pulled to Quicklisp AND I'd already been commenting on that!! 

My bad - scatterbrained...

I'd also add the conditional compilation to use the sb-ext:string-to-octets though - something like this?
```common lisp
(defun string-to-utf8 (string)
  "Convert STRING to UTF-8.  Return a vector of unsigned-bytes."
  ;; Use built-in function on CLISP.
  #+clisp (ext:convert-string-to-bytes string 'charset:utf-8)
  #+sbcl (sb-ext:string-to-octets string :external-format :utf-8)
  #-(or sbcl clisp) (string-to-utf8-lisp string))
```
